// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdnjcqarylspvpfingge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbmpjcWFyeWxzcHZwZmluZ2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTg4ODMsImV4cCI6MjA1NzgzNDg4M30.UlPnV_s39sMXUMWwGoQ6-gHGpN7XmE-QwWPUgrqm6iM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);